name: geofencing_api
description: "This plugin is used to implement circular and polygon geofencing service."
version: 1.4.0
homepage: https://github.com/Dev-hwang/geofencing_api

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

  meta: ^1.12.0
  vector_math: ^2.1.4
  fl_location: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.pravera.geofencing_api
        pluginClass: GeofencingApiPlugin
      ios:
        pluginClass: GeofencingApiPlugin
      web:
        pluginClass: GeofencingApiWeb
        fileName: geofencing_api_web.dart
